#!/usr/bin/env bash

FACTORY_AUTH_BASIC_USERNAME="${FACTORY_AUTH_BASIC_USERNAME:-factory}"
API_AUTH_CURL_ARGS=()

if [[ -n "${FACTORY_AUTH_BASIC_PASSWORD:-}" ]]; then
  API_AUTH_CURL_ARGS=(-u "${FACTORY_AUTH_BASIC_USERNAME}:${FACTORY_AUTH_BASIC_PASSWORD}")
fi
